spring:
  datasource:
    url: jdbc:mysql://43.142.82.171:3306/chatgpt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: lq123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:/data.yml

server:
  servlet:
    # 应用的访问路径
    context-path: /
  port: 8080
